[package]
name = "fj-export"
version = "0.6.0"
edition = "2021"

description = "The world needs another CAD program."
readme = "../../README.md"
homepage = "https://www.fornjot.app/"
repository = "https://github.com/hannobraun/fornjot"
license = "0BSD"
keywords = ["cad", "programmatic", "code-cad"]
categories = ["encoding", "mathematics", "rendering"]


[dependencies]
threemf = { git = "https://github.com/freylint/3mf-rs.git", branch = "feature/wasm32" }

[dependencies.fj-interop]
version = "0.6.0"
path = "../fj-interop"

[dependencies.fj-math]
version = "0.6.0"
path = "../fj-math"
