[package]
name = "fj-viewer"
version = "0.6.0"
edition = "2021"

description = "The world needs another CAD program."
readme = "../../README.md"
homepage = "https://www.fornjot.app/"
repository = "https://github.com/hannobraun/fornjot"
license = "0BSD"
keywords = ["cad", "programmatic", "code-cad"]
categories = ["encoding", "mathematics", "rendering"]


[dependencies]
futures = "0.3.21"
thiserror = "1.0.31"
tracing = "0.1.34"
winit = "0.26.1"

[dependencies.fj-gfx]
version = "0.6.0"
path = "../fj-gfx"

[dependencies.fj-gui]
version = "0.6.0"
path = "../fj-gui"

[dependencies.fj-host]
version = "0.6.0"
path = "../fj-host"

[dependencies.fj-input]
version = "0.6.0"
path = "../fj-input"


[dependencies.fj-interop]
version = "0.6.0"
path = "../fj-interop"

[dependencies.fj-math]
version = "0.6.0"
path = "../fj-math"

[dependencies.fj-operations]
version = "0.6.0"
path = "../fj-operations"
