[package]
name = "fj-host"
version = "0.6.0"
edition = "2021"

description = "The world needs another CAD program."
readme = "../../README.md"
homepage = "https://www.fornjot.app/"
repository = "https://github.com/hannobraun/fornjot"
license = "0BSD"
keywords = ["cad", "programmatic", "code-cad"]
categories = ["encoding", "mathematics", "rendering"]

[target.'cfg(target_family = "wasm")'.dependencies]
web-sys = "0.3.57"

[target.'cfg(not(target_family = "wasm"))'.dependencies]
libloading = "0.7.2"

[dependencies]
notify = "5.0.0-pre.15"
thiserror = "1.0.31"

[dependencies.fj]
version = "0.6.0"
path = "../fj"
