---
# Source: https://github.com/hendrikmaus/rust-workflows
#
# Continuous Integration Workflow For Rust
name: CI

# Define the triggers; usually merges to the repository
# default branch and pull-requests
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

env:
  CARGO_TERM_COLOR: always
  # A list of flags to pass to rustc when executing clippy.
  #
  # Used at check time to enforce quality of pull requests.
  CLIPPY_RUSTC_FLAGS: "-D missing-docs"

defaults:
  run:
    shell: bash

jobs:
  fmt:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up toolchain
        uses: oxidecomputer/actions-rs_toolchain@oxide/master
        # see https://github.com/actions-rs/toolchain/pull/209
        # uses: actions-rs/toolchain@v1
        with:
          override: true
          profile: minimal
          target: ${{ matrix.target }}
      - name: Run `cargo fmt`
        uses: actions-rs/cargo@4ff6ec2846f6e7217c1a9b0b503506665f134c4b
        with:
          command: fmt
          args: --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up toolchain
        uses: oxidecomputer/actions-rs_toolchain@oxide/master
        # see https://github.com/actions-rs/toolchain/pull/209
        # uses: actions-rs/toolchain@v1
        with:
          override: true
          profile: minimal
          target: ${{ matrix.target }}
      - name: Install Clippy
        run: rustup component add clippy
      - name: Set up Rust cache
        uses: Swatinem/rust-cache@1232abb8968faf344409165de17cbf9e7f340fd8
      - name: Run `cargo clippy`
        uses: actions-rs/clippy-check@9d09632661e31982c0be8af59aeb96b680641bc4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features -- $CLIPPY_RUSTC_FLAGS

  export:
    name: Validate 3MF Export
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up toolchain
        uses: oxidecomputer/actions-rs_toolchain@oxide/master
        # see https://github.com/actions-rs/toolchain/pull/209
        # uses: actions-rs/toolchain@v1
        with:
          override: true
          profile: minimal
          target: ${{ matrix.target }}
      - name: Set up Rust cache
        uses: Swatinem/rust-cache@1232abb8968faf344409165de17cbf9e7f340fd8
      - name: Run `export-validator`
        uses: actions-rs/cargo@4ff6ec2846f6e7217c1a9b0b503506665f134c4b
        with:
          command: run
          args: --package export-validator

  test:
    name: Test
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
    runs-on: ${{matrix.os}}
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up toolchain
        uses: oxidecomputer/actions-rs_toolchain@oxide/master
        # see https://github.com/actions-rs/toolchain/pull/209
        # uses: actions-rs/toolchain@v1
        with:
          override: true
          profile: minimal
          target: ${{ matrix.target }}
      - name: Set up Rust cache
        uses: Swatinem/rust-cache@1232abb8968faf344409165de17cbf9e7f340fd8
      - name: Run `cargo build`
        uses: actions-rs/cargo@4ff6ec2846f6e7217c1a9b0b503506665f134c4b
        with:
          command: build
      - name: Run `cargo test`
        uses: actions-rs/cargo@4ff6ec2846f6e7217c1a9b0b503506665f134c4b
        with:
          command: test
